version: 0.2
    
phases:
  install:
    runtime-versions:
      nodejs: latest
    commands:
      - echo Installing app dependencies...
      - echo Run "yarn install"...
      - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | head -c 7) 
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - echo Logging in to Amazon ECR...
      - echo Build files...
  build:
    commands:
      - echo Entered the build phase...
      - echo Building the Docker image...
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Pushing the Docker image...
